import Head from "next/head";
import { useEffect } from "react";
import Image from "next/image";
import PrimaryButton, {
  SecondaryButton,
  ThirdButton,
} from "../components/button/button";
import styles from "../styles/Home.module.css";

//? Import from Libraries
import Tilt from "react-parallax-tilt";

//? Import Assets
import logo from "../assets/logo.png";
import myHeroImage from "../assets/me-hero.png";
import aboutImage from "../assets/about-me.png";
import Line from "../components/line";
import Skills from "../components/skills/card";
import Special from "../components/special/special";
import Portfolio from "../components/portfolio/portfolio";

//* -------------------------------- Home Component ------------------------------- */
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <header className="mb-32">
          <nav className="navbar w-full flex justify-between py-8">
            <div className="logo ">
              <Image src={logo} width="100%" height="40px" />
            </div>
            <div>
              <SecondaryButton>Let's Chat</SecondaryButton>
            </div>
          </nav>
          <div className="hero relative w-full">
            <div className="hero-wrapper relative h-full w-full flex flex-col xl:flex-row justify-around gap-4 items-center text-center xl:text-left">
              <div className="hero-content xl:w-1/2">
                <div className="xl:w-1/2 2xl:w-2/3 z-10 xl:absolute left-0 top-1/2 xl:-translate-y-1/2">
                  <h1 className="leading-tight mb-4">
                    I design and develop websites that converts
                  </h1>
                  <PrimaryButton>Get in touch</PrimaryButton>
                </div>
              </div>
              <div className="hero-image relative">
                <Tilt transitionSpeed={800}>
                  <div className="absolute left-1/2 bottom-0 -translate-x-1/2 bg-gray-200 h-[400px] xl:h-[550px] w-[600px] xl:w-[600px]"></div>
                  <div className="heroImage h-[500px] xl:h-[600px] w-[600px] xl:w-[700px]">
                    <Image
                      src={myHeroImage}
                      layout="fill"
                      objectFit="contain"
                      className=""
                    />
                  </div>
                </Tilt>
              </div>
            </div>
            <Line />
          </div>
        </header>
        <div className="about-me section flex flex-col-reverse  gap-8 mt-8">
          <div className="about-content flex-1 flex flex-col  my-auto">
            <h2 className="mb-2">ABOUT ME</h2>
            <p className="font-regular mb-8 xl:mb-6">
              I'm Aissa, a Frontend Developer with extensive experience in web
              development. I have a knack for creating projects from scratch,
              and have built several projects for both business and pleasure. My
              self-taught knowledge of web development has been cultivated
              through reading hundreds of blogs and watching countless videos.
              This year, I've been working on a variety of projects, which I
              approach with creativity, organization, and enthusiasm for new
              technologies. <br /> <br /> I have a strong work ethic and am
              dedicated to continually improving my skills and knowledge. I am
              confident in providing clients with the best solutions for their
              web development needs.{" "}
            </p>
            <SecondaryButton>let's discuss it</SecondaryButton>
          </div>
        </div>
        <div className="skills section">
          <h2>I USE VARIOUS TECHNOLOGIES</h2>
          <Skills />
        </div>
        <div className="section text-center relative p-4">
          <h2>WHAT MAKES ME SPECIAL</h2>
          <Special />
          <Line tailwindRotation="rotate-1" />
        </div>
        <div className="section text-center ">
          <div>
            <h3 className="text-blue-light">HERE IS THE GOOD PART</h3>
            <h2 className="mb-6">SOME OF MY RECENT WORKS</h2>
          </div>
          <div className="relative">
            <Portfolio />
          </div>
        </div>
        <div className="h-72">
          <div className="h-72 flex flex-col gap-4 justify-center items-center w-screen absolute left-1/2 -translate-x-1/2 text-center bg-blue-light">
            <h2 className="text-white">Let's get to wrok together !</h2>
            <PrimaryButton className=" text-blue-dark font-bold bg-light hover:bg-gray-100 active:bg-white">
              Get in touch
            </PrimaryButton>
            <Line
              tailwindRotation="-rotate-1"
              className="z-50 bg-light text-dark "
              textClass="text-dark"
            />
          </div>
        </div>
        <div className="flex -z-10 items-center justify-between px-[20%] h-44 w-screen absolute left-1/2 -translate-x-1/2 bg-blue ">
          <div className="logo ">
            <Image src={logo} width="100%" height="40px" />
          </div>
          <nav className="flex gap-4">
            <span className="text-white">Work</span>
            <span className="text-white">Contact</span>
            <span className="text-white">My skills</span>
          </nav>
        </div>
      </main>
    </div>
  );
}
