import Head from "next/head";
import { useEffect } from "react";
import Image from "next/image";
import PrimaryButton, {
  SecondaryButton,
  ThirdButton,
} from "../components/button/button";
import styles from "../styles/Home.module.css";

//? Import from Libraries
import Tilt from "react-parallax-tilt";

//? Import Assets
import logo from "../assets/logo.png";
import myHeroImage from "../assets/me-hero.png";
import aboutImage from "../assets/about-me.png";
import Line from "../components/line";
import Skills from "../components/skills/card";
import Special from "../components/special/special";
import Portfolio from "../components/portfolio/portfolio";

//* -------------------------------- Home Component ------------------------------- */
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <header className="mb-32">
          <nav className="navbar w-full flex justify-between py-8">
            <div className="logo ">
              <Image src={logo} width="100%" height="40px" />
            </div>
            <div>
              <SecondaryButton>Let's Chat</SecondaryButton>
            </div>
          </nav>
          <div className="hero py-6 relative">
            <div className="hero-wrapper flex justify-between">
              <div className="hero-content relative">
                <div className="absolute bottom-1/2 translate-y-1/2 left-0 w-[50vw] z-10">
                  <h1 className="text-8xl font-bold mb-8">
                    I design and develop websites that converts
                  </h1>
                  <PrimaryButton>Get in touch</PrimaryButton>
                </div>
              </div>
              <div className="hero-image w-max h-max pr-10 relative">
                <Tilt transitionSpeed={800}>
                  <div className="relative w-[600px] h-[650px] bg-gray-300"></div>
                  <div className="heroImage">
                    <Image
                      src={myHeroImage}
                      layout="fill"
                      objectFit="contain"
                    />
                  </div>
                </Tilt>
              </div>
            </div>
            <Line />
          </div>
        </header>
        <div className="about-me section flex gap-8 mt-8">
          <Image
            src={aboutImage}
            className="flex-1
          "
            width={600}
            height={700}
            objectFit="cover"
          />
          <div className="about-content max-w-3xl flex-1 flex flex-col gap-6 my-auto">
            <h2>ABOUT ME</h2>
            <p>
              I'm Aissa, a Frontend Developer with extensive experience in web
              development. I have a knack for creating projects from scratch,
              and have built several projects for both business and pleasure. My
              self-taught knowledge of web development has been cultivated
              through reading hundreds of blogs and watching countless videos.
              This year, I've been working on a variety of projects, which I
              approach with creativity, organization, and enthusiasm for new
              technologies. <br /> <br /> I have a strong work ethic and am
              dedicated to continually improving my skills and knowledge. I am
              confident in providing clients with the best solutions for their
              web development needs.{" "}
            </p>
            <SecondaryButton>let's discuss it</SecondaryButton>
          </div>
        </div>
        <div className="skills section">
          <h2>I USE VARIOUS TECHNOLOGIES</h2>
          <Skills />
        </div>
        <div className="section text-center relative p-4">
          <h2>WHAT MAKES ME SPECIAL</h2>
          <Special />
          <Line tailwindRotation="rotate-1" />
        </div>
        <div className="section text-center">
          <div>
            <h3 className="text-blue-light">HERE IS THE GOOD PART</h3>
            <h2>SOME OF MY RECENT WORKS</h2>
          </div>
          <Portfolio />
        </div>
      </main>
    </div>
  );
}
