import Head from "next/head";
import { useEffect, useState } from "react";
import Image from "next/image";
import PrimaryButton, { SecondaryButton } from "../components/button/button";
import styles from "../styles/Home.module.css";
import "animate.css";

//? Import from Libraries
import Tilt from "react-parallax-tilt";

//? Import Assets
import Line from "../components/line";
import Skills from "../components/skills/card";
import Special from "../components/special/special";
import Portfolio from "../components/portfolio/portfolio";
import Project from "../components/project/Project";
import animateOnScroll from "../utils/animation";

//* -------------------------------- Home Component ------------------------------- */
export default function Home() {
  const [showProjectModal, setShowProjectModal] = useState({
    state: false,
    data: {
      title: "",
      images: [],
      techs: [],
    },
  });

  useEffect(() => {
    let eventId = window.addEventListener("scroll", animateOnScroll);
    console.log(eventId);
    return () => window.removeEventListener("scroll", eventId);
  }, []);

  return (
    <div className="min-w-screen max-w-screen overflow-hidden">
      <Head>
        <title>Aissa Semaoui Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <header className="section ">
          <nav className="navbar w-full flex justify-between py-2 md:py-4 lg:py-8">
            <div className="logo w-24 lg:w-32">
              <Image
                src="/content/staticImages/logo.png"
                layout="responsive"
                width="152px"
                height="54px"
                alt="My logo"
              />
            </div>
            <div>
              <SecondaryButton
                href="https://github.com/aissa0347"
                className="py-2 px-6"
              >
                My Github
              </SecondaryButton>
            </div>
          </nav>
          <div className="hero relative w-full pt-4">
            <div className="hero-wrapper relative h-full w-full flex flex-col xl:flex-row justify-around gap-4 items-center text-center xl:text-left">
              <div className="hero-content xl:w-1/2">
                <div className="xl:w-1/2 2xl:w-2/3 z-10 xl:absolute left-0 top-1/2 xl:-translate-y-1/2">
                  <h1 className="leading-tight mb-4">
                    I design and develop websites that converts
                  </h1>
                  <PrimaryButton
                    href="https://www.upwork.com/freelancers/~01cfe9b8ec808399c0"
                    className="mt-2 active:scale-95"
                  >
                    Hire me on Upwork
                  </PrimaryButton>
                </div>
              </div>
              <div className="hero-image relative">
                <Tilt transitionSpeed={800}>
                  <div className="absolute left-1/2 bottom-0 -translate-x-1/2 bg-gray-200 h-[250px] md:h-[350px] xl:h-[550px] w-[350px] md:w-[450px] xl:w-[600px]"></div>
                  <div className="heroImage h-[300px] md:h-[400px] xl:h-[600px] w-[400px] md:w-[500px] xl:w-[700px]">
                    <Image
                      src="/content/staticImages/me-hero.png"
                      layout="fill"
                      objectFit="contain"
                      className=""
                      alt="Personal image"
                    />
                  </div>
                </Tilt>
              </div>
            </div>
            <Line />
          </div>
        </header>
        <div
          id="about-me"
          className="about-me section flex gap-8 mt-16 md:mt-24"
        >
          <div className="w-1/3 max-xl:hidden">
            <img src="/content/staticImages/about-me.png" layout="responsive" />
          </div>
          <div className="about-content flex-1 flex flex-col  my-auto">
            <h2 className="mb-2">ABOUT ME</h2>
            <p className="font-regular mb-4 xl:mb-6">
              I am Aissa, a Frontend Developer with extensive experience in web
              development. I have a knack for creating projects from scratch,
              and have built several projects for both business and pleasure. My
              self-taught knowledge of web development has been cultivated
              through reading hundreds of blogs and watching countless videos.
              This year, I have been working on a variety of projects, which I
              approach with creativity, organization, and enthusiasm for new
              technologies. <br /> <br /> I have a strong work ethic and am
              dedicated to continually improving my skills and knowledge. I am
              confident in providing clients with the best solutions for their
              web development needs.{" "}
            </p>
            <SecondaryButton>lets discuss it</SecondaryButton>
          </div>
        </div>
        <div id="skills" className="skills section text-center">
          <h2>I USE VARIOUS TECHNOLOGIES</h2>
          <Skills />
        </div>
        <div id="special" className="special section text-center relative p-4">
          <h2 className="">WHAT MAKES ME SPECIAL</h2>
          <Special />
          <Line tailwindRotation="rotate-1" />
        </div>
        <div id="portfolio" className="portfolio section text-center ">
          <div>
            <h3 className="text-blue-light">HERE IS THE GOOD PART</h3>
            <h2 className="mb-6">SOME OF MY RECENT WORKS</h2>
          </div>
          <div className="relative">
            <Portfolio setShowProjectModal={setShowProjectModal} />
          </div>
        </div>
        <div id="contact" className="contact h-72 lg:h-80">
          <div className="h-72 lg:h-80 max-w-screen px-4 flex flex-col gap-8 justify-center items-center w-screen absolute left-1/2 -translate-x-1/2 text-center bg-blue-light">
            <h2 className="text-white max-md:text-3xl xl:text-6xl">
              Lets get to work together&nbsp;!
            </h2>
            <SecondaryButton
              href="https://www.upwork.com/freelancers/~01cfe9b8ec808399c0"
              className="text-dark hover:text-dark font-bold border-none px-8 lg:px-16 md:py-4 bg-gray-100 hover:bg-white active:bg-gray-100 shadow-sm active:shadow-none active:scale-95"
            >
              Get in touch
            </SecondaryButton>
            <Line
              tailwindRotation="-rotate-1"
              className="z-50 bg-light text-dark "
              textClass="text-dark"
            />
          </div>
        </div>
        <div
          id="footer"
          className="footer flex flex-col-reverse gap-4 md:flex-row -z-10 items-center justify-center md:justify-around pt-4 h-44 w-screen absolute left-1/2 -translate-x-1/2 bg-blue "
        >
          <div className="logo w-24 lg:w-32">
            <Image
              src="/content/staticImages/logoWhite.png"
              layout="responsive"
              width="152px"
              height="54px"
              alt="My logo"
            />
          </div>
          <nav className="flex gap-4">
            <span className="text-white cursor-pointer hover:text-gray-200">
              <a>Work</a>
            </span>
            <span className="text-white cursor-pointer hover:text-gray-200">
              <a>Contact</a>
            </span>
            <span className="text-white cursor-pointer hover:text-gray-200">
              <a>My skills</a>
            </span>
          </nav>
        </div>
      </main>
      <div>
        <Project
          showProjectModal={showProjectModal}
          setShowProjectModal={setShowProjectModal}
        />
      </div>
    </div>
  );
}
